# Generated by Django 5.2.7 on 2025-10-27 19:40

import django.db.models.deletion
import medics.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the patient",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "patient_id",
                    models.CharField(
                        blank=True,
                        help_text="Unique identifier for the patient",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "contact_number",
                    models.CharField(
                        help_text="Contact number of the patient", max_length=15
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Patient creation timestamp"
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient",
                "verbose_name_plural": "Patients",
                "db_table": "Patient",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TestType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the test type",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of the test type", null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Test type creation timestamp"
                    ),
                ),
            ],
            options={
                "verbose_name": "Test Type",
                "verbose_name_plural": "Test Types",
                "db_table": "TestType",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Facility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the patient",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "contact_number",
                    models.CharField(
                        help_text="Contact number of the laboratory", max_length=15
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Facility creation timestamp"
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        help_text="Users associated with the facility",
                        related_name="facilities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Facility",
                "verbose_name_plural": "Facilities",
                "db_table": "Facility",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Referral",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=medics.models.generate_referral_id,
                        editable=False,
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "clinical_notes",
                    models.TextField(
                        blank=True,
                        help_text="Clinical notes for the referral",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="Pending",
                        help_text="Status of the referral",
                        max_length=10,
                    ),
                ),
                (
                    "referred_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Referral creation timestamp"
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        help_text="Facility to which the patient is referred",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facility",
                        to="medics.facility",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        help_text="Patient being referred to the laboratory",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient",
                        to="medics.patient",
                    ),
                ),
                (
                    "referred_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who referred the patient",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referred_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "test_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Type of test being referred",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_type",
                        to="medics.testtype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Referral",
                "verbose_name_plural": "Referrals",
                "db_table": "Referral",
                "ordering": ["-referred_at"],
            },
        ),
    ]
