# Generated by Django 5.2.7 on 2025-10-27 19:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="facility",
            name="contact_number",
            field=models.CharField(
                blank=True,
                help_text="Contact number of the laboratory",
                max_length=15,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="facility",
            name="users",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users associated with the facility",
                null=True,
                related_name="facilities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
