# Generated by Django 5.2.7 on 2025-10-27 20:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medics", "0002_alter_facility_contact_number_alter_facility_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="contact_number",
            field=models.CharField(
                blank=True,
                help_text="Contact number of the patient",
                max_length=15,
                null=True,
            ),
        ),
    ]
