# Generated by Django 5.2.7 on 2025-10-27 20:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medics", "0003_alter_patient_contact_number"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="facility",
            name="users",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users associated with the facility",
                related_name="facilities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
