# Generated by Django 5.2.7 on 2025-10-30 08:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medics", "0004_alter_facility_users"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="full_name",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="patient_id",
        ),
        migrations.AddField(
            model_name="patient",
            name="full_name_or_id",
            field=models.CharField(
                blank=True,
                help_text="Name or IDof the patient",
                max_length=255,
                null=True,
            ),
        ),
    ]
