# Generated by Django 5.2.7 on 2025-10-30 08:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medics", "0005_remove_patient_full_name_remove_patient_patient_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="referral",
            options={"verbose_name": "Referral", "verbose_name_plural": "Referrals"},
        ),
        migrations.AlterField(
            model_name="referral",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("RECEIVED", "Received"),
                    ("COMPLETED", "Completed"),
                ],
                default="Pending",
                help_text="Status of the referral",
                max_length=10,
            ),
        ),
    ]
