# Generated by Django 5.2.7 on 2025-11-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medics", "0006_alter_referral_options_alter_referral_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the test",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of the test", null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Test creation timestamp"
                    ),
                ),
            ],
            options={
                "verbose_name": "Test",
                "verbose_name_plural": "Tests",
                "db_table": "Test",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="testtype",
            name="tests",
            field=models.ManyToManyField(
                blank=True,
                help_text="Tests associated with this test type",
                related_name="test_types",
                to="medics.test",
            ),
        ),
    ]
