# Generated by Django 5.2.7 on 2025-11-05 19:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medics", "0007_test_testtype_tests"),
    ]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, help_text="Test creation timestamp"
            ),
        ),
    ]
