# Generated by Django 5.2.7 on 2025-11-05 19:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("medics", "0008_alter_test_created_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="test",
            options={
                "ordering": ["-name"],
                "verbose_name": "Test",
                "verbose_name_plural": "Tests",
            },
        ),
    ]
