# Generated by Django 5.2.7 on 2025-11-05 19:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medics", "0010_alter_test_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="facility",
            name="test_types",
            field=models.ManyToManyField(
                blank=True,
                help_text="Test types available at the facility",
                related_name="facilities",
                to="medics.testtype",
            ),
        ),
    ]
