# Generated by Django 5.2.7 on 2025-11-05 20:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("medics", "0011_facility_test_types"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="facility",
            options={
                "ordering": ["name"],
                "verbose_name": "Facility",
                "verbose_name_plural": "Facilities",
            },
        ),
        migrations.AlterModelOptions(
            name="referral",
            options={
                "ordering": ["-referred_at"],
                "verbose_name": "Referral",
                "verbose_name_plural": "Referrals",
            },
        ),
        migrations.AlterModelOptions(
            name="testtype",
            options={
                "ordering": ["name"],
                "verbose_name": "Test Type",
                "verbose_name_plural": "Test Types",
            },
        ),
    ]
