# Generated by Django 5.2.7 on 2025-11-05 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medics", "0012_alter_facility_options_alter_referral_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="referral",
            name="test_type",
        ),
        migrations.AddField(
            model_name="referral",
            name="test",
            field=models.ForeignKey(
                blank=True,
                help_text="Type of test being referred",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test",
                to="medics.test",
            ),
        ),
    ]
