# Generated by Django 5.2.7 on 2025-11-05 23:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medics", "0013_remove_referral_test_type_referral_test"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="referral",
            name="referred_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Doctor who referred the patient",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="referred_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
