# Generated by Django 5.2.7 on 2025-11-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medics", "0014_alter_referral_referred_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referral",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Received", "Received"),
                    ("Completed", "Completed"),
                ],
                default="Pending",
                help_text="Status of the referral",
                max_length=10,
            ),
        ),
    ]
