# Generated by Django 5.2.7 on 2025-11-09 18:46

from django.db import migrations


def update_referral_statuses(apps, schema_editor):
    Referral = apps.get_model('medics', 'Referral')
    Referral.objects.filter(status='PENDING').update(status='Pending')
    Referral.objects.filter(status='RECEIVED').update(status='Received')
    Referral.objects.filter(status='COMPLETED').update(status='Completed')


class Migration(migrations.Migration):
    dependencies = [
        ("medics", "0015_alter_referral_status"),
    ]

    operations = [
        migrations.RunPython(update_referral_statuses),
    ]
