# Generated by Django 5.2.7 on 2025-11-12 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medics", "0016_update_referral_statuses"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="referral",
            name="test",
        ),
        migrations.CreateModel(
            name="ReferralTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "referral",
                    models.ForeignKey(
                        help_text="Referral associated with the test",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referral_tests",
                        to="medics.referral",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        help_text="Test associated with the referral",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referral_tests",
                        to="medics.test",
                    ),
                ),
            ],
            options={
                "verbose_name": "Referral Test",
                "verbose_name_plural": "Referral Tests",
                "db_table": "ReferralTest",
                "unique_together": {("referral", "test")},
            },
        ),
    ]
