# Generated by Django 5.2.7 on 2025-11-12 19:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medics", "0017_remove_referral_test_referraltest"),
    ]

    operations = [
        migrations.AddField(
            model_name="referraltest",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="ReferralTest creation timestamp",
            ),
        ),
        migrations.AddField(
            model_name="referraltest",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Received", "Received"),
                    ("Completed", "Completed"),
                ],
                default="Pending",
                help_text="Status of the referral test",
                max_length=10,
            ),
        ),
    ]
