# Generated by Django 5.2.7 on 2025-11-23 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medics", "0018_referraltest_created_at_referraltest_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="facility",
            name="test_types",
        ),
        migrations.RemoveField(
            model_name="testtype",
            name="tests",
        ),
        migrations.AddField(
            model_name="referral",
            name="completed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when the referral was completed",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="referral",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Referral last update timestamp"
            ),
        ),
        migrations.AddField(
            model_name="referraltest",
            name="completed_at",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp when the test was completed", null=True
            ),
        ),
        migrations.AddField(
            model_name="referraltest",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="ReferralTest last update timestamp"
            ),
        ),
        migrations.AddField(
            model_name="test",
            name="test_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Type of the test",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tests",
                to="medics.testtype",
            ),
        ),
        migrations.AddField(
            model_name="testtype",
            name="facilities",
            field=models.ManyToManyField(
                help_text="Facilities offering this test type",
                related_name="test_types",
                to="medics.facility",
            ),
        ),
        migrations.AlterField(
            model_name="facility",
            name="name",
            field=models.CharField(
                blank=True, help_text="Name of the facility", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="full_name_or_id",
            field=models.CharField(
                blank=True,
                help_text="Name or ID of the patient",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="referral",
            name="facility",
            field=models.ForeignKey(
                blank=True,
                help_text="Facility to which the patient is referred",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="referrals",
                to="medics.facility",
            ),
        ),
        migrations.AlterField(
            model_name="referral",
            name="patient",
            field=models.ForeignKey(
                help_text="Patient being referred to the laboratory",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="referrals",
                to="medics.patient",
            ),
        ),
        migrations.AlterField(
            model_name="referral",
            name="referred_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Doctor who referred the patient",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="medical_practitioner",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
