# Generated by Django 5.2.7 on 2025-11-23 19:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medics", "0019_remove_facility_test_types_remove_testtype_tests_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Price of the test",
                max_digits=10,
            ),
        ),
    ]
