# Generated by Django 5.2.7 on 2025-11-24 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medics", "0020_test_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="facility",
            field=models.ForeignKey(
                blank=True,
                help_text="Facility offering the test",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tests",
                to="medics.facility",
            ),
        ),
    ]
