# Generated by Django 5.2.7 on 2025-11-24 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medics", "0021_test_facility"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="test",
            name="facility",
        ),
        migrations.RemoveField(
            model_name="testtype",
            name="facilities",
        ),
        migrations.AddField(
            model_name="testtype",
            name="facility",
            field=models.ForeignKey(
                blank=True,
                help_text="Facility offering this test type",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test_types",
                to="medics.facility",
            ),
        ),
    ]
