# Generated by Django 5.2.7 on 2025-12-04 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medics", "0022_remove_test_facility_remove_testtype_facilities_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="facility",
            name="users",
        ),
        migrations.RemoveField(
            model_name="referral",
            name="facility",
        ),
        migrations.AddField(
            model_name="facility",
            name="admin",
            field=models.ForeignKey(
                blank=True,
                help_text="Administrator of the facility",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="facility_admin",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="FacilityBranch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the facility branch",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Facility branch creation timestamp",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        help_text="Facility to which this branch belongs",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branches",
                        to="medics.facility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Facility Branch",
                "verbose_name_plural": "Facility Branches",
                "db_table": "Facility_Branch",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="referral",
            name="facility_branch",
            field=models.ForeignKey(
                blank=True,
                help_text="Facility branch to which the patient is referred",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="referrals",
                to="medics.facilitybranch",
            ),
        ),
        migrations.CreateModel(
            name="BranchTechnician",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_admin",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if the technician has admin privileges at the branch",
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the technician was assigned",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Lab technician assigned to the branch",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branch_technicians",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        help_text="Facility branch to which the technician is assigned",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="technicians",
                        to="medics.facilitybranch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Branch Technician",
                "verbose_name_plural": "Branch Technicians",
                "db_table": "Branch_Technician",
                "unique_together": {("user", "branch")},
            },
        ),
    ]
