# Generated by Django 5.2.7 on 2025-12-04 22:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medics", "0023_remove_facility_users_remove_referral_facility_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="facilitybranch",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Indicates if the branch is active"
            ),
        ),
    ]
