# Generated by Django 5.2.7 on 2025-10-27 20:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("MEDICAL_PRACTITIONER", "Medical Practitioner"),
                    ("LAB_TECHNICIAN", "Lab Technician"),
                    ("PATIENT", "Patient"),
                ],
                default="Medical Practitioner",
                help_text="Type of user",
                max_length=30,
            ),
        ),
    ]
